### ISSUE TITLE
Warning: Extra attributes from the server: class,style at html

### ISSUE THREAD

**Issue by rodriguezz4060** [stormhead-org/stormic#19]
to remove the Warning 
`Warning: Extra attributes from the server: class,style at html`
you can use **suppressHydrationWarning** in app/layout.tsx

`<html lang='en' suppressHydrationWarning>`

**this doesn't solve the problem, but as a temporary solution you can use**

[found a solution:](https://github.com/stormhead-org/stormic/pull/20#issue-2528104933)

**Comment by nimscore** [comment]
Fixed in pull request #20
