### ISSUE TITLE
Ошибка при отправке комментария

### ISSUE THREAD

**Issue by Butonix** [stormhead-org/stormic#21]
При отправке комментария, в консоле имеется ошибка
`GET /p/undefined 200 in 42ms
 ⨯ PrismaClientValidationError: 
Invalid `prisma.post.findUnique()` invocation:

{
  where: {
+   post_id: Int
  }
}

Argument `post_id` is missing.
    at async PostPage (p/[id]/page.tsx:33:18)
digest: "2264779885"
`

**Comment by nimscore** [comment]
Спасибо, что проявили интерес. Это не совсем актуальная вещь, т.к. вы используете не совсем рабочую версию, которая не может собраться в prod билд. Я думаю, что сегодня уже обновлю ветки гитхаба и вы сможете снова все проверить )
